# Setup
title:        jordyf.com
tagline:      All in all you're just another user in the web
baseurl:      ""
paginate:     1

# About/contact
author:       Jordy Ferreira
  name:       Jordy Ferreira
  url:        http://github.com/fenexomega

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
theme: jekyll-theme-hacker
